#+DATE: <2021-03-02 Tue 16:43>
#+TITLE: 了不起的杰弗里斯
#+OPTIONS: num:nil \n:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css"/>

** TL;DR

   #+begin_quote
   这是一篇关于姐夫许愿机制的文章
   大部分转载自 https://www.newyx.net/gl/611255_1.htm 并进行了fix
   #+end_quote

** 许愿机制

   #+begin_quote
   姐夫会根据可编码的已知信息，在许愿池中进行检索，根据若干写好的模式进行匹配，匹配的结果根据“完美程度”进行排序，输出优先级前三的结果。
   #+end_quote

** 许愿信息

   ◆ _姐夫知道什么？_

   - 双方血量 
   - 双方手牌数量 
   - 双方随从数量 
   - 每个随从的身材、种族和关键词异能 如是否有亡语 
   - 双方的武器和奥秘 
   - 自己的场攻 
   
   ◆ _姐夫不知道什么_

   - 自己手牌的具体内容 
   - 每个随从的非关键词特效及BUFF 
   - 对方的奥秘的可能分布 
   - 战场BUFF如洛欧塞布、风潮 
   - 随从之间的COMBO 
   
   ◆ _疑似不知道_

   - 双方的技能 
   - 自己手牌的费用和种类 

** 许愿池

   许愿池只包括基础和经典卡，包含九职业和中立卡牌；许愿池不包括荣誉室卡牌；

   解场牌，在任何情况下，价值不高于1费打2、2费打3的牌，不在许愿池内；

   随从牌，在任何情况下，价值不高于每费最强生物的牌，不在许愿池内；

   所有奥秘牌不在许愿池内；

   回手牌不在许愿池内：如年轻的酒仙、年迈的酒仙、暗影步；

   需要配合的牌不在许愿池内：如奥金尼灵魂祭司、大法师安东尼达斯；

   模型被其他牌完爆的牌不在许愿池内：如变形术、凯恩·血蹄、银背族长；

   收益不稳定的牌不在许愿池内：如奥术飞弹、复仇之怒、炎魔之王拉格纳罗斯；

   无法编码在任何许愿模式，从而不在许愿池内：如激活、苔原犀牛、末日预言者；

   确定在许愿池，但触发条件未知：如加拉克苏斯大王、星辰坠落、角斗士的长弓；

   不确定是否在许愿池：如、伺机待发、剑刃乱舞；

** 许愿模式

*** 斩杀模式

    触发条件：对方进入斩杀线

    直接伤害：炎爆，血吼，火球，熔岩爆裂，影袭

    铺场BUFF：嗜血、咆哮、风怒、心灵之火、疯狂的炼金师

    过墙：群体驱散、沉默

    其他：红龙

    有时候无法直接斩杀时，也会给出嗜血、咆哮、炎爆进行跨回合斩杀。

*** AOE模式

    触发条件：对方不少于3个怪

    最强AOE：扭曲虚空、绝命乱斗

    伤害AOE：烈焰风暴、神圣新星、奉献、暴风雪、暗影烈焰、闪电风暴、刀扇、魔爆术、冰霜新星、横扫、旋风斩、地狱烈焰

    生物AOE：精神控制技师、迦顿男爵、恐惧地狱火

    未确定条件：星辰坠落、关门放狗、剑刃乱舞

    不会发现：生而平等、爆炸陷阱、末日预言家、憎恶、奥术飞弹、复仇之怒

*** 质量生物模式

    触发条件：双方空场，或对面随从不多

**** 每费最强

     1费：烈焰小鬼

     2费：精灵龙、巫师学徒

     3费：动物伙伴

     4费：水元素

     5费：利爪德鲁伊

     6费：长鬃草原狮

     7费：战争古树

     8费：提里奥·弗丁

     ◆ _手牌不多于4张：_

     1费：真言术：盾

     2费：战利品贮藏者

     3费+：光明之翼

     7费：疾跑

     9费：伊瑟拉

     ◆ _手牌不少于6张：_ 山岭巨人、暮光幼龙

     ◆ _对面手牌不少于9张：_ 穆克拉

     有武器时：恐怖海盗

     打过2张牌：范克里夫

     死过2个怪：大检察官怀特迈恩

     缺嘲讽怪：虚空行者、土元素、战争古树

     低于5费：野性成长

     血量安全：真银圣剑、刺客之刃、血吼
     
**** 特殊单解模式
     
     触发条件：只要满足条件必定触发

     对面有0攻怪：疯狂的炼金师

     对面有2攻怪：秘教暗影祭司、狂奔科多兽

     对面有3攻高血怪：暗言术：痛

     对面有5攻怪：暗言术：灭

     对面有7攻怪：王牌猎人、精神控制

     对面有受伤大怪：斩杀

     对面只有一个大怪：致命射击

     6费对面有大怪：灵魂虹吸

     对面有恶魔：牺牲契约

     对面有鱼人：鱼人杀手蟹

     对面有嘲讽：黑骑士

     对面有多个圣盾：血骑士

     对面有武器：酸性软泥怪、哈里森琼斯

     对面有奥秘：军情七处渗透者、照明弹

**** 回血模式

     触发条件：血量较低

     治疗之触、列王守卫、圣疗术、圣光术、盾牌格挡

**** 随从交换模式

     触发条件：任何复杂场面、或其他模式不足三个选项

     半AOE：背叛、爆炸射击、多重射击、叉状闪电、顺劈斩

     节奏卡：军情七处特工、背刺、刺骨、死亡缠绕

     群体BUFF：阿古斯防御者、野性之力、丛林之魂、野性赐福

     单体BUFF：真言术：盾、心灵之火、狂暴、野性印记、驯兽师

     保底选项：王者祝福

*** 许愿优先级

    #+begin_quote
    姐夫的许愿优先级依据每张牌的场面价值改变函数进行排序，该函数的具体细节仍在探索中。以下仅给出部分经验性结论：
    #+end_quote    
    
    ◆ _整体优先级_ 

    斩杀 > 群解 > 回血 > 群体BUFF > 节奏随从 > 质量随从 > 单解 > 拆武器/拆奥秘

    本回合剩余费用 > 下回合满费用

    有条件牌 > 无条件牌

    ◆ _质量随从：优先级从高到低_

    大检察官怀特迈恩：死过2个怪

    伊瑟拉：缺手牌

    战争古树：缺高血墙

    提里奥·弗丁

    范克里夫：打过3张卡

    山岭巨人：手牌有6张

    长鬃草原狮

    范克里夫：打过2张卡

    穆克拉：对方手牌有9张

    暮光幼龙：手牌有6张

    利爪德鲁伊

    水元素

    动物伙伴

    恐怖海盗：有武器

    精灵龙、巫师学徒

    烈焰小鬼

    ◆ _拆武器/拆奥秘_

    拆武器/拆奥秘的优先级较低，只有在对方场面价值低时才会给出；

    拆单个奥秘，军情七处渗透者优先级高于照明弹；

    拆多个奥秘，照明弹优先级最高；

    ◆ _沉默_

    沉默嘲讽、圣盾、亡语的优先级很低，几乎不会出现；

    可以过墙斩杀时，姐夫会给出群体驱散或沉默；

    对方只有一个带亡语大怪，姐夫会给出妖术；

    沉默加攻加血BUFF的优先级等同于解场；

    如对面有一排蹦蹦兔，姐夫会给出群体驱散。

*** 如何许愿

    ◆ _控制变量_

    控制费用：手里有硬币时先打出硬币，想得到低费牌先用掉部分费用；

    控制场面：纯粹的场面几乎必定许愿得到想要的选项，但复杂场面有时许愿失败；

    控制斩杀：许愿斩杀时，需要将手牌中所有伤害提前打出；

    ◆ _了解姐夫_

    熟悉常见的许愿选项分布

    对面铺满怪，必定许愿得到AOE；

    双方空场，必定许愿得到最强生物；

    对面有4个怪，必定许愿得到精神控制技师；

    自己有4个怪，必定许愿得到丛林之魂；

    对方有恶魔、鱼人、嘲讽、单个打怪，必定许愿得到对应单解；

    ◆ _许愿失败_

    破奥秘，军情七处渗透者优先级高于照明弹；

    姐夫不会考虑对面的奥秘是冰箱的可能性；

    没有特殊属性的5/5随从，不会得到任何单解； 说的就是你，索瑞森大帝！

    空场死过2个随从，大检察官怀特迈恩会挤掉提里奥弗丁的位置。

    ◆ _姐夫的bug_

    目前姐夫已知的BUG不多，全部出现在斩杀领域。

    6费对方空场8血，姐夫不会给出复仇之怒；

    5费己方场上有若干睡眠野兽，可以冲锋斩杀，姐夫不会给出苔原犀牛；

    己方没有武器，姐夫会误以为英雄无法攻击，不会给出咆哮；

    姐夫会将突袭错判为冲锋，误以为可以斩杀，给出嗜血或咆哮；

    姐夫无法区分护甲和血量，误以为可以斩杀，给出红龙；
